[package]
name = "chapulin"
version = "0.1.0"
authors = ["DanielRivasMD <danielrivasmd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

# tsv = "0.1.1"



#build = "build.rs"
#categories = ["command-line-utilities", "development-tools", "visualization"]
#description = "A utility that allows you to count code, quickly."
#edition = "2018"
#homepage = "https://tokei.rs"
#include = ["Cargo.lock", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT", "build.rs", "languages.json", "src/**/*"]
#keywords = ["utility", "cli", "cloc", "lines", "statistics"]
#license = "MIT/Apache-2.0"
#readme = "README.md"
#repository = "https://github.com/XAMPPRocky/tokei.git"
