[package]
name = "chapulin"
version = "0.1.0"
authors = ["DanielRivasMD <danielrivasmd@gmail.com>"]
edition = "2018"


[[bin]]
name = "chapulin"
path = "src/bin/main.rs"
doc = false


[lib]
name = "chapulin"
path = "src/chapulin.rs"


[dependencies]
libc = "0.2.70"